SDL2 Support
cosmoscout/vista pull request #24
Opened 2023-07-14 09:41 UTC by JonasGilg

This PR adds the following things:

- A new SDL2 Windowing Toolkit
- A driver for an SDL2 Keyboard
- A driver for an SDL2 Mouse
- A driver for an SDL2 Controller
  - The controller driver should be able to handle all controllers, that look like an XBox or Playstation controller.

Currently the PR is in a robust and functional state, but some minor tasks remain:
- [ ] Extensive documentation
- [ ] Improve the loading of fonts and controller DB
- [ ] Controller touchpad support (somehow missed that during the first implementation)
- [ ] SDL2_ttf CMake find script isn't following Vistas pattern
- [ ] Offer SDL2 OpenVR windowing toolkit?

Things that are possible, but probably go in another PR:
- Handling of multiple windows in Keyboard, Mouse and Controller drivers
- SDL2 force feedback driver
- SDL2 touch and multitouch driver
- SDL2 audio driver

2023-09-06 15:12 UTC, JonasGilg commented
If you require I can add some script in the coming days guiding through a test setup.

2023-11-07 13:30 UTC, Schneegans requested changes
Thanks a lot! This is a really cool improvement.

2023-11-07 13:30 UTC, Schneegans commented on VistaCoreLibs/VistaKernel/DisplayManager/SDL2WindowImp/VistaSDL2WindowingToolkit.cpp
> +      , blitFboDepthId(0) {
Maybe these could be initialized inline?

2023-11-07 13:30 UTC, Schneegans commented on VistaDemo/configfiles/display_desktop.ini
>  WINDOWINGTOOLKIT	= GLUT
Should this default to SDL2 now?

2023-11-29 16:09 UTC, JonasGilg commented
It is actually possible to allow SDL to handle controller input without window focus using the following hint: `SDL_SetHint( SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS, "1" );`

Should we enable it?

2023-12-05 07:48 UTC, Schneegans approved these changes

2023-12-05 08:23 UTC, merged